apiVersion: apps/v1
kind: Deployment
metadata:
  name: easyorder-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easyorder-database
  template:
    metadata:
      name: easyorder-database
      labels:
        app: easyorder-database
    spec:
      containers:
        - name: easyorder-database-container
          image: mysql:9.0.1
          resources:
            limits:
              memory: "1000Mi"
              cpu: "1000m"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: easyorder-database-persistent-storage
              mountPath: /var/lib/mysql
          envFrom:
            - configMapRef:
                name: easyorder-database-configmap
                optional: true
      volumes:
        - name: easyorder-database-persistent-storage
          persistentVolumeClaim:
            claimName: pvc-easyorder-database