apiVersion: apps/v1
kind: Deployment
metadata:
  name: easyorder-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: easyorder
  template:
    metadata:
      name: easyorder
      labels:
        app: easyorder
    spec:
      automountServiceAccountToken: false
      containers:
      - name: easyorder-container
        image: brunomoreirareis/easyorder-app-cliente:v1.0.0
        resources:
          limits:
            memory: "1000Mi"
            cpu: "500m"
            ephemeral-storage: "2Gi"
          requests:
            memory: "500Mi"
            cpu: "250m"
            storage: "1Gi"
        ports:
        - containerPort: 30000
        envFrom:
        - configMapRef:
            name: easyorder-configmap
            optional: true
        volumeMounts:
        - name: easyorder-storage
          mountPath: /data
      volumes:
      - name: easyorder-storage
        emptyDir: {}