apiVersion: apps/v1
kind: Deployment
metadata:
  name: easyorder-app-produto-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: easyorder-app-produto
  template:
    metadata:
      name: easyorder-app-produto
      labels:
        app: easyorder-app-produto
    spec:
      automountServiceAccountToken: false
      containers:
      - name: easyorder-app-produto-container
        image: brunomoreirareis/easyorder-app-produto:latest
        resources:
          limits:
            memory: "1000Mi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          requests:
            memory: "500Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: easyorder-app-produto-configmap
            optional: true