apiVersion: v1
kind: ConfigMap
metadata:
  name: easyorder-app-produto-database-configmap
data:
  MONGO_INITDB_DATABASE: easyorder
  MONGO_INITDB_ROOT_USERNAME: easyorder_mongo_username
  MONGO_INITDB_ROOT_PASSWORD: easyorder_mongo_password10
 