apiVersion: v1
kind: Service
metadata:
  name: svc-easyorder-app-produto
spec:
  type: LoadBalancer
  selector:
    app: easyorder-app-produto
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
